-- Create a table for system-wide settings
CREATE TABLE IF NOT EXISTS settings (
    id bigint generated by default as identity primary key,
    key text unique not null,
    value text not null,
    description text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Turn on RLS
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;

-- Allow read access to everyone (public)
CREATE POLICY "Enable read access for all users" ON settings
    FOR SELECT USING (true);

-- Allow update access only to admins (you can refine this later with proper roles)
-- For now, we'll allow Authenticated users to update if we don't have a strict Admin Role yet, 
-- OR strictly restrict to specific emails if possible. 
-- Ideally: 
-- CREATE POLICY "Enable update for admins only" ON settings FOR UPDATE USING (auth.email() IN ('dekaandassociate@gmail.com'));
-- For the immediate MVP to allow you to edit from Admin Panel:
CREATE POLICY "Enable all access for authenticated users" ON settings
    FOR ALL USING (auth.role() = 'authenticated');

-- Insert default commission
INSERT INTO settings (key, value, description)
VALUES ('referral_commission', '10', 'Percentage commission for referrals')
ON CONFLICT (key) DO NOTHING;
